#define REAGENT_BASE_CHEMICAL 1
#define REAGENT_STANDARD_CHEMICAL 2
#define REAGENT_RARE_CHEMICAL 4
#define REAGENT_RARE_MEDICINE 8
#define REAGENT_BLACKLISTED_CHEMICAL 16 //Blacklist for random chemicals
#define REAGENT_SAFE_CHEMICAL 32
#define REAGENT_DRINK 64